### ISSUE TITLE
Where I put the channel name?

### ISSUE THREAD

**Issue by ozerr** [ohyou/twitch-viewer#6]
So I dont know how to pass arguments in python.
I get this error when I try to run the script.
![image](https://cloud.githubusercontent.com/assets/7794956/18656408/879dc596-7ef9-11e6-8950-f8e70ddbc642.png)

**Comment by ohyou** [comment]
Run from command prompt as follows: `python twitch-viewer.py channelname`

May also be `python.exe` or a full path to your python binaries.

**Comment by Asexual** [comment]
Won't matter initially regardless if you resolve your issue as right now kraken will return you with a 400 error resulting in the script to currently be depreicated until an oauth header is sent via livestreamer --twitch-oauth-token xxxxxxxxxxxxxxxxxxxx twitch.tv/channel best otherwise it will no longer work. @ohyou for you the kraken api has updated so if you want to either let the public know to end confusion because i am sure a lot of people will paste the same catch error you have when reading json from kraken.

**Comment by HellBz** [comment]
Yes I got the same problem..

**Comment by ozerr** [comment]
Thanks for the fast answer. I got it now how arguments works xD. But Ive got this error now. The channel name is correct. I guess is somthing wrong with livesteamer? Should livestreamer get installed inside my python libs? Because now its on program files.

error: An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?

Or it might be as @Asexual  mentioned somthing with the updated api?

**Comment by ohyou** [comment]
Could you provide the full error text, and if it mentions a line in the code, the part of code as well?

**Comment by ozerr** [comment]
Where is the full error text located?

**Comment by ohyou** [comment]
Just screenshot whatever it says for you and send here. Or otherwise copy and paste it here, but use the code formatting.

**Comment by krvs** [comment]
![image](https://cloud.githubusercontent.com/assets/8191755/18724824/7bdde760-8046-11e6-83b5-74e2c5f10020.png)

**Comment by ohyou** [comment]
Thanks for the information. I'll get that fixed by the end of the week.

**Comment by ozerr** [comment]
I get the exactly same error as @krvs posted. It would be cool if you can fix it :)
One last question, does it support only http proxies or it can run with socks proxies also?

**Comment by ohyou** [comment]
It only supports http proxy

**Comment by HellBz** [comment]
and fixed ??

**Comment by ozerr** [comment]
Just check when he will update the code, its 7 days ago the last update.

**Comment by ohyou** [comment]
Should work now.

**Comment by rdvo** [comment]
im still getting this error saying channel is offline but its def online. Ideas?
